### ISSUE TITLE
ファイルを追加したときに同名のフォルダが同時に追加される

### ISSUE THREAD

**Issue by maihrs55** [violet-ts/violet#100]
- ファイルを追加したときに同名のフォルダがもう一つ追加され、
    その下にファイルが作成される動きをしていました。
    - おそらく追加した順番に並べようとしている動きかなと思われます。 

![image](https://user-images.githubusercontent.com/52160187/141673488-b312913d-c5f9-4a37-862b-94cef5f0233d.png)

**Comment by shuheiest** [comment]
確認ありがとうございます。
イシュー対応時に修正します。
