### ISSUE TITLE
info.json を取得して１ファイルあたり複数ページ表示

### ISSUE THREAD

**Issue by maihrs55** [violet-ts/violet#112]
### Overview
- ApiRevision, BrowserRevisionにinfo.jsonのパスを追加
- Info.jsonからページ数と拡張子を取得して、ページごとのパスを作成
- フロントからURLでイメージを取得

### ToDo
- Info .json取得のポーリングは別イシューを立てました
    - #130 
    - 本イシューに対応したら、画面の動きが重くなってしまったため。余計な処理を修正します

**Comment by LumaKernel** [comment]
minio はデフォルトでバケットポリシーが private になってるから mc 使って pubilc にする必要がありそう

policy いじるコマンドはこれ: https://docs.min.io/docs/minio-client-complete-guide.html#policy

そうすれば、 minio admin 側で share すると presigned url が手に入るんだけど、 query parameter 省いてもアクセスできることが確認できる。ホスト部は `localhost` に書き換えてね。
