### ISSUE TITLE
lint-staged を入れる

### ISSUE THREAD

**Issue by LumaKernel** [violet-ts/violet#125]
コミット時に差分が出たファイルのみをフォーマットかけられる

**Comment by LumaKernel** [comment]
VSCode の件解決したしいらんかなあ？

**Comment by solufa** [comment]
個人的には時間がかかるlint-staged好きではない
コミットのたびに待たされるのが辛い
微妙な修正をサクッとamendすることが多くてストレスたまりがち
ので極力ファイル保存時に整形してCIに任せたい

**Comment by LumaKernel** [comment]
それはすごいわかります。

lint-staged 単体は lint fix の高速化に使えんこともないが…どうか、と。とりあえずすごいほしいなどではない。
あとは husky 一般の話ですけど、他の人が触るときに安全側に倒す目的で入れておいて、自分は HUSKY=0 で過ごすことが多い
