### ISSUE TITLE
null / undefined を統一

### ISSUE THREAD

**Issue by solufa** [violet-ts/violet#133]
optionalと併用できるしundefinedかな・・・

**Comment by LumaKernel** [comment]
- JSON まで持ち込めるのは `null` (例えば配列内に登場するとかなら null しかない)
- `function (n: number | undefined = 0)` に `undefined` を渡すすべがない

などあって、「明示的に nullable を指定する場面がありうる/値としてその指定自体が意味を持つなら `null`」みたいな考えで使うことがおおくて、あんまり統一したいと思うことはないですねー。上記のような `undefined` にしかない特性もありますし、TS のおかげでこれ関連のバグも埋めにくくなった気がして

**Comment by solufa** [comment]
今のところはちゃんと型定義すればOK

**Comment by solufa** [comment]
関数の返り値にはnullを使うように意識しよう（Lintにないから気付かずマージすることは折り込む）

`(): hoge | null => {}`
