### ISSUE TITLE
プロジェクト名とプロジェクトアイコンをアップデート時のエラー対応

### ISSUE THREAD

**Issue by shuheiest** [violet-ts/violet#138]
プロジェクト名とプロジェクトアイコンをアップデートするときに以下のエラーが表示されてしまうため修正を行う。
「Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.」

**Comment by LumaKernel** [comment]
useEffect, イベント系で asynchronous な処理したあとになにかする場合は注意が必要。まあちょっと汚いけど cancel でやろうとするとこうなる。

```ts
useEffect(() => {
  let canceled = false;
  void (async() => {
    const some = await callApi()
    if (canceled) return;
    setSome(some)
  })();
  return () => { canceled = true; }
})
```

できるなら、変更だけして、あとは SWR で mutate に全部まかせて一方通行で再計算するのが綺麗だと思う。
