### ISSUE TITLE
tsxファイルで200行超えてもエラーが表示されない

### ISSUE THREAD

**Issue by shuheiest** [violet-ts/violet#162]
あるべき動作として、200行を超えた場合は200行以降は赤く線が引かれて欲しいが
今は200行超えても赤く線が引かれないため見逃してしまう可能性がる。(CIかrun lintで気付く)
![スクリーンショット 2021-12-19 17 08 24](https://user-images.githubusercontent.com/88891567/146668120-6e874a2a-537a-4460-82f2-a7b720665976.png)

**Comment by solufa** [comment]
これは他の人の環境では再現しなさそう

**Comment by shuheiest** [comment]
使用しているPCにインストールしているnodeのバージョンがv16だったため、eslintrc.jsの
`execFileSync('pnpm', ['--filter=./pkg', 'list', '--depth', '-1', '--no-color'], {
  cwd: __dirname,
}`
が動作できなかった。
node v14をPCにインストールすることで正常にeslintが動作するようになった。
正常に動作できるようになったため、クローズします。
