### ISSUE TITLE
[RFC] add Makefile

### ISSUE THREAD

**Issue by hashue** [violet-ts/violet#182]
Makefileを追加することで効率化できそう。ただ、現状 dbログインぐらいしかMakefileが使えそうな場所がないのでRFCとした。

**Comment by hashue** [comment]
dockerコマンドは全てMakefileで入力が効率化できそう

**Comment by LumaKernel** [comment]
dbログインはone-offのタスクではないしMakefileは使わなくないですか？
dockerコマンドもdocker-comopseのことであれば、これ自体dockerをラップしていて私はこれで十分な粒度だと思っています。

**Comment by hashue** [comment]
なるほど。個人的にdockerとmakeはセットなところがあるので、issue立てた感じです。
(毎回docker-composeとか打つの面倒だし、前職コマンドのtypoでエラー報告を何度もされたので…)
