### ISSUE TITLE
環境別Seed作成

### ISSUE THREAD

**Issue by maihrs55** [violet-ts/violet#35]
- a.開発環境・テスト環境とb.本番環境で別のSeedを使用する
    - aではprisma/seedData.tsでSeedを投入
    - bではJsonで定義し、JasonParseしてSeedを投入
- seed.ts をa,b 両環境で使用できるソースに修正する

**Comment by LumaKernel** [comment]
seed-dev.ts とか seed-huge.ts, seed-specials.ts みたいにしておいてもらえれば `/prisma/db/seed huge` みたいに注入できるようにします

**Comment by LumaKernel** [comment]
あ、なるほど、すでにあるのか。

https://github.com/violet-ts/violet/issues/76

これをこれから作業するついでに見てみます。 assign は私に張り替えておきます。
なにか構想や作業途中のものあれば教えて下さい。
