### ISSUE TITLE
認証 (Cognito、Identity Platform、...) 関連の実装

### ISSUE THREAD

**Issue by LumaKernel** [violet-ts/violet#52]
git branch → Firebase を抜く → pnpm → Cognito の準備、の順で行う

Cognito は期待の新星 https://github.com/localstack/localstack というのがあるが、やるかは微妙。結局 localstack と AWS どちらに開発用途のお金を払うかという話になりそう。ただ使ってみてすごいよかった、という場合は検討します。

**Comment by LumaKernel** [comment]
この前話していた Cognito + React のなにか、よかったら貼ってください～ @solufa

**Comment by solufa** [comment]
https://zenn.dev/dove/articles/63494de652511c
この記事見てました
デザインやログイン状態の保持など細かいところは別チケットでやればいいので放置していいですよ

**Comment by LumaKernel** [comment]
- Cognito は sign in with OAuth 対応していない
- GitHub は OAuth しか実装していない
  - 自分で Cognito が欲しいエンドポイントを実装することは可能といえば可能
    - https://github.com/TimothyJones/github-cognito-openid-wrapper
    - あまりやりたくはない
  - FusionAuth を使うと OAuth をラップして OIDC に対応させられる https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/github/
- (localstack は pro 版でしか Cognito が使えず、機能も限定的)
- Firebase Auth を復帰させようと思ったが、Firebase Auth は sign in with SAML に対応していない
  - https://cloud.google.com/identity-platform/docs/product-comparison
- Identity Platform (GCP) は sign in with OAuth も sign in with SAML も対応

Identity Platform にしてみようかと少し思っています。

**Comment by LumaKernel** [comment]
ローカルのみで動くようにはするつもりです。どのレベルでの差異吸収をするかは検討中です。

**Comment by LumaKernel** [comment]
Identity Platform 、Firebase Auth と互換性がありそう。というか使い方ほぼ同じそう。

以下、復帰するかもしれないのでメモ。

削除時 PR https://github.com/violet-ts/violet/pull/63
https://github.com/violet-ts/violet/tree/db331d4c7ae04d804e98c7ec71093aead3570883
https://github.com/violet-ts/violet/blob/db331d4c7ae04d804e98c7ec71093aead3570883/pages/components/UserBanner.tsx
