### ISSUE TITLE
S3のディレクトリ階層を1つ深くする

### ISSUE THREAD

**Issue by solufa** [violet-ts/violet#64]
violet-appのBucketにディレクトリを作りやすくしたい

asis: violet-appの直下にProjectIdが並んでいるので他の用途のディレクトリを作りづらい
tobe: violet-app/works/{workId}/revisions/...とか？lambdaの変換結果を扱いやすい構成にする

コンテナを作りなおせば消えるのでメンバーのDockerに残るデータの削除は不要

リリース後にこういう操作をする場合はバッチを書いてマイグレーションが必要になる

**Comment by LumaKernel** [comment]
自動削除とかのルールを変えたい場合もあると思うのでそのときは相談してください。
tmp 用に3日で消える、とか。

**Comment by LumaKernel** [comment]
https://github.com/violet-ts/violet/issues/96 別 issue のつもりで書いたがもしかして同じかな？

**Comment by LumaKernel** [comment]
bucket 分けるとしても、1段階深くしておくのがいいでしょうね

**Comment by LumaKernel** [comment]
Cognito やったあとに、conv2img のデプロイついでにやることになると思うので、まだであればやろうと思います。

**Comment by solufa** [comment]
私含めて誰もやってないですね
Cognito周りも触れてない
