### ISSUE TITLE
Lambdaでの変換に失敗することがある

### ISSUE THREAD

**Issue by solufa** [violet-ts/violet#66]
https://github.com/violet-ts/violet/pull/65#issuecomment-957497506

再現方法が判明したら対応

**Comment by solufa** [comment]
@maihrs55 
変換されなかったPDFのファイル名にスペースは含まれていましたか？

**Comment by LumaKernel** [comment]
失敗時の `docker-compose logs lambda` の内容はどうですか。

**Comment by solufa** [comment]
私の手元にあるほとんどのPDFを変換できるようになってPR作成できそうです
これで解決するかどうかはわからんけど

**Comment by maihrs55** [comment]
@solufa 
アンダースコアを削除するとoriginal/convertedが作成されます。
すみません、原因わからなかったので、アップロードしたpdfを添付します。
[Uploading Weekend_ザッカーバーグの見ている景色_Quartz_Japan_Quartz.pdf…]()

**Comment by maihrs55** [comment]
@LumaKernel 
[Weekend：ザッカーバーグの見ている景色 — Quartz Japan — Quartz.pdf](https://github.com/violet-ts/violet/files/7487480/Weekend.Quartz.Japan.Quartz.pdf)

エラーになっているファイルはこちらでした。
PDF自体は同じものです。

[lambda.log](https://github.com/violet-ts/violet/files/7487488/lambda.log)

エラーログも合わせて添付します。

**Comment by LumaKernel** [comment]
空白処理っぽいね。 PR のもので治るのではないかな？

**Comment by solufa** [comment]
@maihrs55 
PRの修正でそのPDFが変換できることを確認できました、ありがとうございます
mainにマージ済みなのでFetchしてみてください

**Comment by maihrs55** [comment]
ハイフンの前後のスペース消したらconverted できました。
