### ISSUE TITLE
pkg/api 配下で一部の型エラーがエディタに表示されない

### ISSUE THREAD

**Issue by solufa** [violet-ts/violet#74]
pkg/api/src/service 内のtsファイルに以下を貼り付けると再現可能
ターミナルではTSErrorが表示されるのであくまでVSCodeの問題

```ts
;[1, 2, 3].find((n) => n === 4).toString()
```

他のpkgではfindがundefinedを返す可能性があるのでエラーを表示してくれる

![image](https://user-images.githubusercontent.com/9402912/140274263-86e75d8f-9e90-4e28-8c6b-f910eb899170.png)

恐らく関連事項
pkg/api/src/validators/index.tsでexperimentalDecoratorsがないと指摘される

![image](https://user-images.githubusercontent.com/9402912/140274797-3078d947-f557-4c7a-bfaa-77d0012c9996.png)

def/tsconfig.jsonがエディタに認識されていない？

**Comment by LumaKernel** [comment]
なるほど。展開しますかね。それっぽい issue は見つからず。

**Comment by LumaKernel** [comment]
vscode 立ち上げてみたけど特に起こらず。 WSL2 につないでいます。
pnpm install はまあしてますよね。
cwd が project-root 以外…とか言うこともないですかね。

**Comment by LumaKernel** [comment]
下のエラーは確認できました。ベタ書きしたら起こらないですね。

**Comment by LumaKernel** [comment]
```
  "exclude": ["node_modules"],
  "include": ["**/*.ts"]
```

これ書いたら治った。
