### ISSUE TITLE
pkg配下の依存関係に制約をかけたい

### ISSUE THREAD

**Issue by solufa** [violet-ts/violet#78]
pkg/web から pkg/api の色々をインポートできる状態が心配ではある

pkg/web, lambda, scripts は他から参照されることがないはず
pkg/def に環境変数やtypes, constants, utilsをまとめたい
pkg/api は $api.ts のみが pkg/web から参照できる状態が理想

というのを pnpm で実現可能だろうか
eslint でも良い

**Comment by LumaKernel** [comment]
できます。
https://eslint.org/docs/rules/no-restricted-imports

この際なので import 系は eslint でやりますか。 prettier plugin のほう、除外オプションなど探したのですが見つかりませんでした。

**Comment by solufa** [comment]
おお！eslintにまとめていいです

**Comment by LumaKernel** [comment]
- VSCode の Organize Imports はいつでも使えるようにしたい

というのを要求としておくと source map support は import ではなく別の方法 (`-r`) でやらないとどうにもならないことがわかったので、 order に関してはそのままにします。

**Comment by LumaKernel** [comment]
> pkg/def に環境変数やtypes, constants, utilsをまとめたい

`types` は prisma に関する re-export があるので全部は動かせなさそうです。

`utils` は `@violet/utils`, `/libs` などでも良いかと思います。 `@violet/def` はなんとなく、artifact に入れてインフラ側から必要な環境変数がわかるようになって嬉しいかもしれない、などというふうに思いました。
