### ISSUE TITLE
ファイル保存・変換の S3 パス構成変更

### ISSUE THREAD

**Issue by LumaKernel** [violet-ts/violet#96]
変換系の from と to は S3 の根本 (一番最初の prefix かそもそもバケットを分ける) から分岐していてもらえると以下のような点で助かる。

- S3 のイベントを拾う際は prefix でしかフィルタできない (extension は別であります)
- アクセス権限は prefix ということはないが、 `/*/converted/*` のようにあまり自明な形にならない (例: converted という名前のプロジェクトやファイル名などがあり得る場合などは？)
- 無限ループをイベントレベル＋権限レベルで阻止したい。それには上記が必要
  - これはスクリプトでも阻止したいところではある。今は、ただ put 先がすでに存在しているから失敗するとかだと思われる (なにかエラーが出る、走ってはいる)

かんたんには、`/converted/...` と `/original/...` にする。バケット分けたほうがいいんじゃないかとも思っている。original のアクセス頻度と converted のアクセス頻度がちがうと思われて、後にこれに基づいた設定ができるなど。

- [ ] bucket vs key prefix どちらにするか決める
- [ ] スクリプト側での無限ループ防止を一応入れておく
- [ ] 上記の変更を violet に適用する
- [ ] 上記基準を wiki に移しておく

**Comment by LumaKernel** [comment]
@solufa bucket にしようかと思っていますが、なにか懸念点あれば教えて下さい

**Comment by LumaKernel** [comment]
うーん。Bucket 分ける明確な意味を決めるまでは、根 prefix だけ分けておけば良いように思えてきた。
Bucket 分ける際には、根 prefix をコピーして同期させ、それで移行するようなイメージ

**Comment by solufa** [comment]
現時点ではどちらにもこだわりないです
